const FETCH_NEW_POKEMON = "FETCH_NEW_POKEMON";
const FETCHING = "FETCHING";
const CONTENT = "CONTENT";
const OFFSET_INCREASE = "OFFSET_INCREASE";

export { FETCH_NEW_POKEMON, FETCHING, CONTENT, OFFSET_INCREASE };
